### ISSUE TITLE
Getting an error while following Matrix-Vector Multiply Example

### ISSUE THREAD

**Issue by haeunlee99** [PolyArch/gem-forge-transform#1]
Hello,

I am following the **Get Started!** page. I have installed all prerequisites and have done the set up. I am trying to execute commands listed in **Matrix-Vector Multiply Example** section, and get following error while executing **cd example && make traced.bc** at GEM_FORGE_TOP directory. I have greped under my root to find **libLLVMTDGPass.so**, but there is no file with such name. At the same time, I can find a bunch of libLLVM*.so files under llvm directory, but none in transform directory. Could someone tell me what I have done wrong?

Thank you in advance :)

> root@2de1f050145e:~/gem-forge-framework/example# make traced.bc
> /root/gem-forge-framework/llvm/install-release/bin/clang /root/gem-forge-framework/transform/benchmark/GemForgeMicroSuite/omp_dense_mv_blk/omp_dense_mv_blk.c -O3 -DGEM_FORGE -mavx512f -fopenmp -std=c11 -gline-tables-only  -c -emit-llvm -I/root/gem-forge-framework/gem5/include -o raw.bc
> /root/gem-forge-framework/llvm/install-debug/bin/opt -instnamer raw.bc -o raw.bc
> /root/gem-forge-framework/llvm/install-debug/bin/opt -load=/root/gem-forge-framework/transform/build/src/libLLVMTDGPass.so -trace-pass raw.bc -o traced.bc -trace-inst-uid-file inst.uid -trace-function .omp_outlined.
> Error opening '/root/gem-forge-framework/transform/build/src/libLLVMTDGPass.so': /root/gem-forge-framework/transform/build/src/libLLVMTDGPass.so: cannot open shared object file: No such file or directory
>   -load request ignored.
> opt: Unknown command line argument '-trace-pass'.  Try: '/root/gem-forge-framework/llvm/install-debug/bin/opt --help'
> opt: Did you mean '--force-pgso'?
> opt: Unknown command line argument '-trace-inst-uid-file'.  Try: '/root/gem-forge-framework/llvm/install-debug/bin/opt --help'
> opt: Did you mean '--time-trace-file'?
> opt: Unknown command line argument '-trace-function'.  Try: '/root/gem-forge-framework/llvm/install-debug/bin/opt --help'
> opt: Did you mean '--print-function'?
> opt: Too many positional arguments specified!
> Can specify at most 1 positional arguments: See: /root/gem-forge-framework/llvm/install-debug/bin/opt --help
> make: *** [Makefile:32: traced.bc] Error 1

**Comment by seanzw** [comment]
Hi. `libLLVMTDGPass.so` should be built after you execute `bash setup.sh`. It contains many LLVM optimization pass, including the stream transformation. Specifically, can you make sure that the commans in `setup.sh` to build GemForge transform succeed?

**Comment by haeunlee22** [comment]
Thanks for reply!

I could see that I no longer get error for the absence of `libLLVMTDGPass.so` after running the setup procedure again. After `make sim-all`, I could see `Simulation all done!`. I guess I did something wrong before. While I have been looking back at the logs for `bash ssp-setup.sh`, I got such messages.

> -- Cannot find llvm-lit.
> -- Please put llvm-lit in your PATH, set OPENMP_LLVM_LIT_EXECUTABLE to its full path, or point OPENMP_LLVM_TOOLS_DIR to its directory.
> CMake Warning at cmake/OpenMPTesting.cmake:22 (message):
>   The check targets will not be available!
> Call Stack (most recent call first):
>   cmake/OpenMPTesting.cmake:51 (find_standalone_test_dependencies)
>   CMakeLists.txt:49 (include)
>
> -- ITT Notify not supported for static libraries - forcing ITT Notify off
> -- Version symbols not supported for static libraries - forcing Version symbols functionality off
>
> -- Cannot find FileCheck.
> -- Please put FileCheck in your PATH, set OPENMP_FILECHECK_EXECUTABLE to its full path, or point OPENMP_LLVM_TOOLS_DIR to its directory.
> CMake Warning at cmake/OpenMPTesting.cmake:33 (message):
>   The check targets will not be available!
> Call Stack (most recent call first):
>   cmake/OpenMPTesting.cmake:51 (find_standalone_test_dependencies)
>   CMakeLists.txt:49 (include)
>
>-- ITT Notify not supported for static libraries - forcing ITT Notify off
>-- Version symbols not supported for static libraries - forcing Version symbols functionality off

The first was solved by `pip3 install lit`, however I could not get rid of second message after trying `pip3 install filecheck` or `sudo apt-get install llvm-8-tools` or `sudo apt-get install llvm-12-tools`. Are those messages ignorable?

Thank you!

**Comment by seanzw** [comment]
I am not sure about these messages. As long as you can compile LLVM feel free to ignore these messages : )
